steps:
# Build the Docker image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/arcs-go-api:$COMMIT_SHA', '.']

# Push the Docker image to Google Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/arcs-go-api:$COMMIT_SHA']

# Deploy to GKE
- name: 'gcr.io/cloud-builders/kubectl'
  args: ['set', 'image', 'deployment/arcs-go-api', 'arcs-go-api=gcr.io/$PROJECT_ID/arcs-go-api:$COMMIT_SHA']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1'
  - 'CLOUDSDK_CONTAINER_CLUSTER=arcs-go-cluster'
