apiVersion: apps/v1
kind: Deployment
metadata:
  name: arcs-go-deployment
  labels:
    app: arcs-go
spec:
  replicas: 3
  selector:
    matchLabels:
      app: arcs-go
  template:
    metadata:
      labels:
        app: arcs-go
    spec:
      serviceAccountName: arcs-go-k8s-service-account # Specify the service account
      containers:
      - name: arcs-go
        image: gcr.io/arcs-391022/arcs-go:$COMMIT_SHA
        ports:
        - containerPort: 8080
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /var/secrets/google/key.json
        volumeMounts:
        - name: google-cloud-key
          mountPath: /var/secrets/google
      volumes:
      - name: google-cloud-key
        secret:
          secretName: k8s-secret
