name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Docker image
      run: docker build -t gcr.io/$PROJECT_ID/arcs-go:$GITHUB_SHA .

    - name: Setup gcloud CLI
      uses: google-github-actions/setup-gcloud@master
      with:
        version: '290.0.1'
        service_account_key: ${{ secrets.GCLOUD_AUTH }}
        project_id: ${{ secrets.PROJECT_ID }}
        export_default_credentials: true

    - name: Push Docker image to GCR
      run: |
        gcloud auth configure-docker
        docker push gcr.io/$PROJECT_ID/arcs-go:$GITHUB_SHA

    - name: Set current Kubernetes context
      run: |
        gcloud container clusters get-credentials arcs-go-cluster --zone us-central1 --project $PROJECT_ID

    - name: Deploy to GKE
      run: |
        kubectl set image deployment/arcs-go-deployment arcs-go=gcr.io/$PROJECT_ID/arcs-go:$GITHUB_SHA
